### ISSUE TITLE
[Un]Official release checklist

### ISSUE THREAD

**Issue by kyle-messier** [NIEHS/GeoTox#61]
### README: make the readme/landing more standard to package landing pages- in order:

- [x] hex logo (new version in development) 
- [x] Brief explanation w/ link to medRxiv https://www.medrxiv.org/content/10.1101/2024.09.23.24314096v1
- [x] Installation guide
- [x] Citation - doc needs update to include medRxiv paper + package
- [x] Issues 
- [x]  Contributing 

### DESCRIPTION

- [x] add ORCID

**Comment by SkylarMarvel** [comment]
Final task of hex logo updated 10/10/2024
